import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header"; 

const SegoeUI = localFont({
  src: "./fonts/SegoeUI.ttf",
  variable: "--font-segoe-ui"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SegoeUI.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
