import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header"; 
import { AuthProvider } from "@/components/providers/auth-provider";
// import { usePathname } from "next/navigation";

const SegoeUI = localFont({
  src: "./fonts/SegoeUI.ttf",
  variable: "--font-segoe-ui"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const showHeader = pathname !== '/login';

  return (
    <html lang="en">
      <body
        className={`${SegoeUI.variable} antialiased`}
      >
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
